const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_CURRENT_PLAYLIST_PLAYING: 'SET_CURRENT_PLAYLIST_PLAYING',

    PLAY: 'PLAY',
    RANDOM: 'RANDOM',
    PLAYLIST: 'PLAYLIST',
    LIST: 'LIST',
    NEW_RELEASE: 'NEW_RELEASE',
    LIVESTREAM: 'LIVESTREAM',

    ARTIST: 'ARTIST',

    GET_NEW_CHART: 'GET_NEW_CHART',

    GET_TOP_100: 'GET_TOP_100',

    GET_SEARCH_DATA: 'GET_SEARCH_DATA',
};

export default actionTypes;
